### ISSUE TITLE
Cirucular importation

### ISSUE THREAD

**Issue by hariharan1412** [BayesRays/BayesRays#9]
Hi, I'm facing some issues with running ns-uncertinity. when i try to run ns-uncertinity it throws circular importation error.

`from nerfstudio.utils.eval_utils import eval_setup
ImportError: cannot import name 'eval_setup' from partially initialized module 'nerfstudio.utils.eval_utils' (most likely due to a circular import) `

File PATH : `/home/ubuntu/workdir/nerfstudio/nerfstudio/utils/eval_utils.py)`
`from nerfstudio.configs.method_configs import all_methods`

This error

**Comment by lilygoli** [comment]
Hi,

you probably have cyclic imports in your files, do you have nerfstudio installed as a package (through pip) or did you clone their repo? I recommend using the package.

**Comment by hariharan1412** [comment]
Yeah i did like you said but I still get different error

`ns-uncertainty --load-config=./project1/old_outputs/inp
ut/nerfacto/2023-11-05_102451/config.yml  --output-path=./project1/bayesRays_out/ 
--lod 8
Traceback (most recent call last):
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 551, in find_python_name
    __import__(module_name)
ModuleNotFoundError: No module named 'nerfstudio.data.datamanagers.parallel_datamanager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/conda/envs/nerfstudio/bin/ns-uncertainty", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/workdir/BayesRays/bayesrays/scripts/uncertainty.py", line 338, in entrypoint
    tyro.cli(ComputeUncertainty).main()
  File "/home/ubuntu/workdir/BayesRays/bayesrays/scripts/uncertainty.py", line 289, in main
    config, pipeline, checkpoint_path, _ = eval_setup(self.load_config)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/utils/eval_utils.py", line 87, in eval_setup
    config = yaml.load(config_path.read_text(), Loader=yaml.Loader)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 620, in construct_python_object
    state = self.construct_mapping(node, deep=deep)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 105, in construct_object
    data = next(generator)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 617, in construct_python_object
    instance = self.make_python_instance(suffix, node, newobj=True)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 722, in make_python_instance
    return super(UnsafeConstructor, self).make_python_instance(
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 585, in make_python_instance
    cls = self.find_python_name(suffix, node.start_mark)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 719, in find_python_name
    return super(UnsafeConstructor, self).find_python_name(name, mark, unsafe=True)
  File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 553, in find_python_name
    raise ConstructorError("while constructing a Python object", mark,
yaml.constructor.ConstructorError: while constructing a Python object
cannot find module 'nerfstudio.data.datamanagers.parallel_datamanager' (No module named 'nerfstudio.data.datamanagers.parallel_datamanager')
  in "<unicode string>", line 92, column 16:
      datamanager: !!python/object:nerfstudio.data. ... `

**Comment by lilygoli** [comment]
It seems nerfstudio is not installed properly as it is not finding this module [here](https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/datamanagers/parallel_datamanager.py). What version of nerfstudio do you have installed? It should work fine using version 3.1 or 3.3.
Can you uninstall nerfstudio and install it again with:

`pip install -e git+https://github.com/nerfstudio-project/nerfstudio.git@e2e5637d05fc281a28abe7c4f9c86a93e130a085#egg=nerfstudio`

This will install a certain commit of nerfstudio with version 3.1 which was tested on my machine.

**Comment by hariharan1412** [comment]
Yeah, I did like you mentioned in your readme.md and now i uninstalled and installed with the given pip command you gave but still it throws the same error 😕. I installed Bays' Rays and nerfbuster also in the conda env

**Comment by lilygoli** [comment]
Could you please confirm if the ns-train command is functioning as expected in your environment? I'm investigating whether this issue stems from a potential corruption during the 'nerfstudio' package installation or if it's related to the uncertainty scripts. While the error trace leads back to nerfstudio, testing 'ns-train' in the same conda environment will help determine if the core 'nerfstudio' functionality is working properly.

Additionally, please be aware that having nerfbusters in the same environment might lead to package conflicts, as both packages share a substantial number of files. This overlap could potentially result in issues related to file pointers and package confusion.

**Comment by hariharan1412** [comment]
Yeah, I understand I already generated a dense point cloud via Nerfstudio. Now I want to remove the noise from the PCD. I saw your work and was really impressed. That's why I want to implement your model on top of my pcd.

the command i used to train is 
`ns-train nerfacto --data input/  --pipeline.model.predict-normals True`

do i have to train any additional parameters ? like `nb-dataparser `

**Comment by lilygoli** [comment]
No, `nb-dataparser` is not required. Considering the error originates from the `eval_setup` function, have you attempted running `ns-viewer` with the same config file to check if the viewer executes without issues? The viewer script in NerfStudio also utilizes the same `eval_setup` function at the beginning of its script to load the model. I'm not sure why one would work while the other is giving this error.

**Comment by smart4654154** [comment]
> Yeah i did like you said but I still get different error
> 
> `ns-uncertainty --load-config=./project1/old_outputs/inp ut/nerfacto/2023-11-05_102451/config.yml --output-path=./project1/bayesRays_out/ --lod 8 Traceback (most recent call last): File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 551, in find_python_name **import**(module_name) ModuleNotFoundError: No module named 'nerfstudio.data.datamanagers.parallel_datamanager'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/ubuntu/conda/envs/nerfstudio/bin/ns-uncertainty", line 8, in sys.exit(entrypoint()) File "/home/ubuntu/workdir/BayesRays/bayesrays/scripts/uncertainty.py", line 338, in entrypoint tyro.cli(ComputeUncertainty).main() File "/home/ubuntu/workdir/BayesRays/bayesrays/scripts/uncertainty.py", line 289, in main config, pipeline, checkpoint_path, _ = eval_setup(self.load_config) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/utils/eval_utils.py", line 87, in eval_setup config = yaml.load(config_path.read_text(), Loader=yaml.Loader) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/**init**.py", line 81, in load return loader.get_single_data() File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data return self.construct_document(node) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document for dummy in generator: File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 620, in construct_python_object state = self.construct_mapping(node, deep=deep) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping return super().construct_mapping(node, deep=deep) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping value = self.construct_object(value_node, deep=deep) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 105, in construct_object data = next(generator) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 617, in construct_python_object instance = self.make_python_instance(suffix, node, newobj=True) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 722, in make_python_instance return super(UnsafeConstructor, self).make_python_instance( File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 585, in make_python_instance cls = self.find_python_name(suffix, node.start_mark) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 719, in find_python_name return super(UnsafeConstructor, self).find_python_name(name, mark, unsafe=True) File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/yaml/constructor.py", line 553, in find_python_name raise ConstructorError("while constructing a Python object", mark, yaml.constructor.ConstructorError: while constructing a Python object cannot find module 'nerfstudio.data.datamanagers.parallel_datamanager' (No module named 'nerfstudio.data.datamanagers.parallel_datamanager') in "", line 92, column 16: datamanager: !!python/object:nerfstudio.data. ... `

I also encountered this problem. I also encountered this problem. Have you solve it?Have you successfully reproduced this project?

**Comment by hariharan1412** [comment]
Sorry, mate, I didn't; I just dropped this project.

**Comment by lilygoli** [comment]
I'm sorry to hear that. I personally can't replicate this issue unfortunately, I'm reopening it so maybe someone else can chime in if they have encountered and fixed it.

**Comment by YGJW27** [comment]
I encountered this problem. I uninstalled nerfstudio, then reinstalled it following Lily's command at version 0.3.1 and bayesrays. Train a new NeRF in the newly installed environment, then calculating and viewing uncertainty are working :)

**Comment by hariharan1412** [comment]
> I encountered this problem. I uninstalled nerfstudio, then reinstalled it following Lily's command at version 0.3.1 and bayesrays. Train a new NeRF in the newly installed environment, then calculating and viewing uncertainty are working :)

Glad to hear that. By the way,  how was the result?

**Comment by YGJW27** [comment]
> > I encountered this problem. I uninstalled nerfstudio, then reinstalled it following Lily's command at version 0.3.1 and bayesrays. Train a new NeRF in the newly installed environment, then calculating and viewing uncertainty are working :)
> 
> Glad to hear that. By the way, how was the result?

Overall, the results were as expected in my own case. However, there are some locations with relatively large depth errors were not assigned with corresponding high uncertainty.
